local ReplicatedStorage = game:GetService("ReplicatedStorage")
local Global            = require(ReplicatedStorage.Global)

return {
	["Square Light"] = {
		icon           = "rbxassetid://74621982442012",
		currency       = Global.Enums.CurrencyEnums.Money,
		lvlRequirement = 1,
		price          = 49.99,
		unitPrice      = 49.99,
		unitSize       = 1,
		model          = ReplicatedStorage.Assets.Products.Decoration["Square Light"],
		category       = Global.Enums.ProductCategories.Decoration,
	},
	
	["Chandelier"] = {
		icon           = "rbxassetid://112815570631904",
		currency       = Global.Enums.CurrencyEnums.Money,
		lvlRequirement = 1,
		price          = 148.99,
		unitPrice      = 148.99,
		unitSize       = 1,
		model          = ReplicatedStorage.Assets.Products.Decoration["Chandelier"],
		category       = Global.Enums.ProductCategories.Decoration,
	},

	["Hanging Light"] = {
		icon           = "rbxassetid://97054839746434",
		currency       = Global.Enums.CurrencyEnums.Money,
		lvlRequirement = 1,
		price          = 68.99,
		unitPrice      = 68.99,
		unitSize       = 1,
		model          = ReplicatedStorage.Assets.Products.Decoration["Hanging Light"],
		category       = Global.Enums.ProductCategories.Decoration,
	},
	
	["Circle Light"] = {
		icon           = "rbxassetid://74948889244057",
		currency       = Global.Enums.CurrencyEnums.Money,
		lvlRequirement = 1,
		price          = 59.49,
		unitPrice      = 59.49,
		unitSize       = 1,
		model          = ReplicatedStorage.Assets.Products.Decoration["Circle Light"],
		category       = Global.Enums.ProductCategories.Decoration,
	},
	
	["Spot Light"] = {
		icon           = "rbxassetid://112346874760342",
		currency       = Global.Enums.CurrencyEnums.Money,
		lvlRequirement = 1,
		price          = 79.29,
		unitPrice      = 79.29,
		unitSize       = 1,
		model          = ReplicatedStorage.Assets.Products.Decoration["Spot Light"],
		category       = Global.Enums.ProductCategories.Decoration,
	},
	
	["Rectangle Light"] = {
		icon           = "rbxassetid://137364719267689",
		currency       = Global.Enums.CurrencyEnums.Money,
		lvlRequirement = 1,
		price          = 88.49,
		unitPrice      = 88.49,
		unitSize       = 1,
		model          = ReplicatedStorage.Assets.Products.Decoration["Rectangle Light"],
		category       = Global.Enums.ProductCategories.Decoration,
	},
	
	["Plant 1"] = {
		icon           = "rbxassetid://78500739183235",
		currency       = Global.Enums.CurrencyEnums.Money,
		lvlRequirement = 1,
		price          = 39.99,
		unitPrice      = 39.99,
		unitSize       = 1,
		model          = ReplicatedStorage.Assets.Products.Decoration["Plant 1"],
		category       = Global.Enums.ProductCategories.Decoration,
	},
	
	["Plant 2"] = {
		icon           = "rbxassetid://118824371019007",
		currency       = Global.Enums.CurrencyEnums.Money,
		lvlRequirement = 1,
		price          = 44.78,
		unitPrice      = 44.78,
		unitSize       = 1,
		model          = ReplicatedStorage.Assets.Products.Decoration["Plant 2"],
		category       = Global.Enums.ProductCategories.Decoration,
	},
	
	["Plant 3"] = {
		icon           = "rbxassetid://133153346932107",
		currency       = Global.Enums.CurrencyEnums.Money,
		lvlRequirement = 1,
		price          = 48.99,
		unitPrice      = 48.99,
		unitSize       = 1,
		model          = ReplicatedStorage.Assets.Products.Decoration["Plant 3"],
		category       = Global.Enums.ProductCategories.Decoration,
	},
}
