local ReplicatedStorage = game:GetService("ReplicatedStorage")
local Global            = require(ReplicatedStorage.Global)

return {
	["Dirty Table"] = {
		icon           = "rbxassetid://96524321356858",
		currency       = Global.Enums.CurrencyEnums.Money,
		lvlRequirement = 1,
		price          = 79.48,
		unitPrice      = 79.48,
		unitSize       = 1,
		model          = ReplicatedStorage.Assets.Products.Furniture["Dirty Table"],
		category       = Global.Enums.ProductCategories.Furniture,
	},
	
	["Garbage"] = {
		icon           = "rbxassetid://90976119153897",
		currency       = Global.Enums.CurrencyEnums.Money,
		lvlRequirement = 1,
		price          = 129.99,
		unitPrice      = 129.99,
		unitSize       = 1,
		model          = ReplicatedStorage.Assets.Products.Furniture["Garbage"],
		category       = Global.Enums.ProductCategories.Furniture,
	},
	
	["Large Dirty Table"] = {
		icon           = "rbxassetid://115816381835605",
		currency       = Global.Enums.CurrencyEnums.Money,
		lvlRequirement = 1,
		price          = 124.99,
		unitPrice      = 124.99,
		unitSize       = 1,
		model          = ReplicatedStorage.Assets.Products.Furniture["Large Dirty Table"],
		category       = Global.Enums.ProductCategories.Furniture,
	},
	
	["Dirty Booth"] = {
		icon           = "rbxassetid://124101316270617",
		currency       = Global.Enums.CurrencyEnums.Money,
		lvlRequirement = 1,
		price          = 99.49,
		unitPrice      = 99.49,
		unitSize       = 1,
		model          = ReplicatedStorage.Assets.Products.Furniture["Dirty Booth"],
		category       = Global.Enums.ProductCategories.Furniture,
	},
	
	["Basic Chair"] = {
		icon           = "rbxassetid://121193016169656",
		currency       = Global.Enums.CurrencyEnums.Money,
		lvlRequirement = 1,
		price          = 39.49,
		unitPrice      = 39.49,
		unitSize       = 1,
		model          = ReplicatedStorage.Assets.Products.Furniture["Basic Chair"],
		category       = Global.Enums.ProductCategories.Furniture,
	},
	
	["Gold Booth"] = {
		icon           = "rbxassetid://82560549016360",
		currency       = Global.Enums.CurrencyEnums.Robux,
		lvlRequirement = 1,
		price          = 0,
		unitSize       = 1,
		model          = ReplicatedStorage.Assets.Products.Furniture["Gold Booth"],
		category       = Global.Enums.ProductCategories.Furniture,
	},
	
	["Gold Table"] = {
		icon           = "rbxassetid://109719060810670",
		currency       = Global.Enums.CurrencyEnums.Robux,
		lvlRequirement = 1,
		price          = 0,
		unitSize       = 1,
		model          = ReplicatedStorage.Assets.Products.Furniture["Gold Table"],
		category       = Global.Enums.ProductCategories.Furniture,
	},
	
	["Large Gold Table"] = {
		icon           = "rbxassetid://73545537513629",
		currency       = Global.Enums.CurrencyEnums.Robux,
		lvlRequirement = 1,
		price          = 0,
		unitSize       = 1,
		model          = ReplicatedStorage.Assets.Products.Furniture["Large Gold Table"],
		category       = Global.Enums.ProductCategories.Furniture,
	},
	
	["Gold Chair"] = {
		icon           = "rbxassetid://104324668394986",
		currency       = Global.Enums.CurrencyEnums.Robux,
		lvlRequirement = 1,
		price          = 0,
		unitSize       = 1,
		model          = ReplicatedStorage.Assets.Products.Furniture["Gold Chair"],
		category       = Global.Enums.ProductCategories.Furniture,
	},
	
	["Large Basic Table"] = {
		icon           = "rbxassetid://139698404786220",
		currency       = Global.Enums.CurrencyEnums.Money,
		lvlRequirement = 6,
		price          = 159.79,
		unitPrice      = 159.79,
		unitSize       = 1,
		model          = ReplicatedStorage.Assets.Products.Furniture["Large Basic Table"],
		category       = Global.Enums.ProductCategories.Furniture,
	},
	
	["Basic Table"] = {
		icon           = "rbxassetid://111613506904162",
		currency       = Global.Enums.CurrencyEnums.Money,
		lvlRequirement = 6,
		price          = 129.99,
		unitPrice      = 129.99,
		unitSize       = 1,
		model          = ReplicatedStorage.Assets.Products.Furniture["Basic Table"],
		category       = Global.Enums.ProductCategories.Furniture,
	},
	
	["Basic Booth"] = {
		icon           = "rbxassetid://125704207285182",
		currency       = Global.Enums.CurrencyEnums.Money,
		lvlRequirement = 6,
		price          = 129.99,
		unitPrice      = 129.99,
		unitSize       = 1,
		model          = ReplicatedStorage.Assets.Products.Furniture["Basic Booth"],
		category       = Global.Enums.ProductCategories.Furniture,
	},
	
	["Modern Chair"] = {
		icon           = "rbxassetid://92946758645799",
		currency       = Global.Enums.CurrencyEnums.Money,
		lvlRequirement = 12,
		price          = 179.49,
		unitPrice      = 179.49,
		unitSize       = 1,
		model          = ReplicatedStorage.Assets.Products.Furniture["Modern Chair"],
		category       = Global.Enums.ProductCategories.Furniture,
	},
	
	["Modern Stool"] = {
		icon           = "rbxassetid://107184769957228",
		currency       = Global.Enums.CurrencyEnums.Money,
		lvlRequirement = 12,
		price          = 149.99,
		unitPrice      = 149.99,
		unitSize       = 1,
		model          = ReplicatedStorage.Assets.Products.Furniture["Modern Stool"],
		category       = Global.Enums.ProductCategories.Furniture,
	},
	
	["Modern Table"] = {
		icon           = "rbxassetid://133009497931493",
		currency       = Global.Enums.CurrencyEnums.Money,
		lvlRequirement = 12,
		price          = 249.99,
		unitPrice      = 249.99,
		unitSize       = 1,
		model          = ReplicatedStorage.Assets.Products.Furniture["Modern Table"],
		category       = Global.Enums.ProductCategories.Furniture,
	},
	
	["Modern Booth"] = {
		icon           = "rbxassetid://109138792685840",
		currency       = Global.Enums.CurrencyEnums.Money,
		lvlRequirement = 12,
		price          = 199.99,
		unitPrice      = 199.99,
		unitSize       = 1,
		model          = ReplicatedStorage.Assets.Products.Furniture["Modern Booth"],
		category       = Global.Enums.ProductCategories.Furniture,
	},
	
	["Luxury Chair"] = {
		icon           = "rbxassetid://108542570991680",
		currency       = Global.Enums.CurrencyEnums.Money,
		lvlRequirement = 18,
		price          = 249.49,
		unitPrice      = 249.49,
		unitSize       = 1,
		model          = ReplicatedStorage.Assets.Products.Furniture["Luxury Chair"],
		category       = Global.Enums.ProductCategories.Furniture,
	},
	
	["Luxury Booth"] = {
		icon           = "rbxassetid://89879439002963",
		currency       = Global.Enums.CurrencyEnums.Money,
		lvlRequirement = 18,
		price          = 399.99,
		unitPrice      = 399.99,
		unitSize       = 1,
		model          = ReplicatedStorage.Assets.Products.Furniture["Luxury Booth"],
		category       = Global.Enums.ProductCategories.Furniture,
	},
	
	["Luxury Table"] = {
		icon           = "rbxassetid://120126807732951",
		currency       = Global.Enums.CurrencyEnums.Money,
		lvlRequirement = 18,
		price          = 499.99,
		unitPrice      = 499.99,
		unitSize       = 1,
		model          = ReplicatedStorage.Assets.Products.Furniture["Luxury Table"],
		category       = Global.Enums.ProductCategories.Furniture,
	},
	
	["Large Luxury Table"] = {
		icon           = "rbxassetid://104236230275527",
		currency       = Global.Enums.CurrencyEnums.Money,
		lvlRequirement = 18,
		price          = 629.49,
		unitPrice      = 629.49,
		unitSize       = 1,
		model          = ReplicatedStorage.Assets.Products.Furniture["Large Luxury Table"],
		category       = Global.Enums.ProductCategories.Furniture,
	},
	
	["Luxury Stool"] = {
		icon           = "rbxassetid://79144509408814",
		currency       = Global.Enums.CurrencyEnums.Money,
		lvlRequirement = 18,
		price          = 239.99,
		unitPrice      = 239.99,
		unitSize       = 1,
		model          = ReplicatedStorage.Assets.Products.Furniture["Luxury Stool"],
		category       = Global.Enums.ProductCategories.Furniture,
	},
}
