

return {
	--burger
	["Paper"] = {
		Icon = "rbxassetid://138927129927753",
	},
	["Burger Bun"] = {
		Icon = "rbxassetid://89681595633241",
	},
	["Cooked Patty"] = {
		Icon = "rbxassetid://138878905774037",
	},
	["Cheese"] = {
		Icon = "rbxassetid://128683448192838",
	},
	["Ketchup"] = {
		Icon = "rbxassetid://112267020637845",
	},
	["Mustard"] = {
		Icon = "rbxassetid://106371449836259",
	},
	["Pickle"] = {
		Icon = "rbxassetid://70655321104856",
	},
	["Onion"] = {
		Icon = "rbxassetid://78181366592977",
	},
	["Tomato"] = {
		Icon = "rbxassetid://81903404441024",
	},
	["Lettuce"] = {
		Icon = "rbxassetid://76182754864355",
	},

	--drinks
	["Empty Soda"] = {
		Icon = "rbxassetid://91706039271454",
	},
	["Large Fanda"] = {
		Icon = "rbxassetid://131098275572528",
	},
	["Large 7Down"] = {
		Icon = "rbxassetid://131098275572528",
	},
	["Large Water"] = {
		Icon = "rbxassetid://131098275572528",
	},
	["Large DrPiper"] = {
		Icon = "rbxassetid://131098275572528",
	},
	["Large Bloxy Cola"] = {
		Icon = "rbxassetid://131098275572528",
	},
	["Large Bug Rootbeer"] = {
		Icon = "rbxassetid://131098275572528",
	},

	--icecreams
	["Ice Cream Cone"] = {
		Icon = "rbxassetid://111082952639307",
	},
	["Vanilla Ice Cream"] = {
		Icon = "rbxassetid://134347548398467",
	},
	["Chocolate Ice Cream"] = {
		Icon = "rbxassetid://116785025974576",
	},
	["Strawberry Ice Cream"] = {
		Icon = "rbxassetid://93988266683404",
	},

	--milkshakes
	["Milkshake Cup"] = {
		Icon = "rbxassetid://94415523906475",
	},
	["Vanilla Milkshake"] = {
		Icon = "rbxassetid://77331156196033",
	},

	--onion rings
	["Raw Onion Rings"] = {
		Icon = "rbxassetid://92012331793579",
	},
	["Cooked Onion Rings"] = {
		Icon = "rbxassetid://92012331793579",
	},
	["Onion Ring Tray"] = {
		Icon = "rbxassetid://133932493537124",
	},
	["Onion Rings"] = {
		Icon = "rbxassetid://92012331793579",
	},

	--fries
	["Raw Fries"] = {
		Icon = "rbxassetid://88246435334985",
	},
	["Cooked Fries"] = {
		Icon = "rbxassetid://88246435334985",
	},
	["Fry Holder"] = {
		Icon = "rbxassetid://91793353222158",
	},
	["Fries"] = {
		Icon = "rbxassetid://91793353222158",
	},

	--nuggets
	["Raw Nuggets"] = {
		Icon = "rbxassetid://132162110024120",
	},
	["Cooked Nuggets"] = {
		Icon = "rbxassetid://132162110024120",
	},
	["Nugget Box"] = {
		Icon = "rbxassetid://79743162753461",
	},
	["Nuggets"] = {
		Icon = "rbxassetid://79743162753461",
	},

	--tray
	["Tray"] = {
		Icon = "rbxassetid://128456322365070",
	},
}
