return {
	["Meal"] = {
		["Burger"] = {
			Lvl = 1,
			Chance = 100,
			Price = 0.49,
			Amount = NumberRange.new(1,1),
			Ingredients = {
				{
					Lvl = 1,
					Chance = 100,
					Price = 1.98,
					Item = "Burger Bun",
				},
				{
					Lvl = 1,
					Chance = 100,
					Price = 2.98,
					Item = "Cooked Patty",
				},
				{
					Lvl = 2,
					Chance = 54,
					Price = 3.98,
					Item = "Cheese",
				},
				{
					Lvl = 15,
					Chance = 30,
					Price = 3.98,
					Item = "Onion",
				},
				{
					Lvl = 20,
					Chance = 30,
					Price = 6.65,
					Item = "Pickle",
				},
				{
					Lvl = 12,
					Chance = 50,
					Price = 3.98,
					Item = "Lettuce",
				},
				{
					Lvl = 3,
					Chance = 30,
					Price = 3.32,
					Item = "Tomato",
				},
			},
		},
		["Nothing"] = {
			Chance = 0,
		},
	},
	["Side"] = {
		["Fries"] = {
			Lvl = 9,
			Chance = 20,
			Price = 4.65,
			Amount = NumberRange.new(1,1),
			Ingredients = {
				{
					Lvl = 1,
					Chance = 100,
					Price = 1.05,
					Item = "Fry Holder",
				},
			},
		},
		["Nuggets"] = {
			Lvl = 18,
			Chance = 75,
			Price = 7.98,
			Amount = NumberRange.new(1,1),
			Ingredients = {
				{
					Lvl = 1,
					Chance = 100,
					Price = 2.65,
					Item = "Nugget Box",
				},
			},
		},
		["Onion Rings"] = {
			Lvl = 30,
			Chance = 150,
			Price = 21.98,
			Amount = NumberRange.new(1,1),
			Ingredients = {
				{
					Lvl = 1,
					Chance = 100,
					Price = 5.98,
					Item = "Onion Ring Tray",
				},
			},
		},
		["Nothing"] = {
			Chance = 5,
		},
	},
	["Drink"] = {
		["Vanilla Milkshake"] = {
			Lvl = 24,
			Chance = 75,
			Price = 10.65,
			Amount = NumberRange.new(1,1),
			Ingredients = {
				{
					Lvl = 1,
					Chance = 100,
					Price = 0,
					Item = "Vanilla Milkshake",
				},
			},
		},
		["Large Fanda"] = {
			Lvl = 6,
			Chance = 75,
			Price = 5.32,
			Amount = NumberRange.new(1,1),
			Ingredients = {
				{
					Lvl = 1,
					Chance = 100,
					Price = 0,
					Item = "Large Fanda",
				},
			},
		},
		["Large 7Down"] = {
			Lvl = 6,
			Chance = 75,
			Price = 3.99,
			Amount = NumberRange.new(1,1),
			Ingredients = {
				{
					Lvl = 1,
					Chance = 100,
					Price = 0,
					Item = "Large 7Down",
				},
			},
		},
		["Large Water"] = {
			Lvl = 6,
			Chance = 75,
			Price = 5.32,
			Amount = NumberRange.new(1,1),
			Ingredients = {
				{
					Lvl = 1,
					Chance = 100,
					Price = 0,
					Item = "Large Water",
				},
			},
		},
		["Large DrPiper"] = {
			Lvl = 6,
			Chance = 75,
			Price = 5.32,
			Amount = NumberRange.new(1,1),
			Ingredients = {
				{
					Lvl = 1,
					Chance = 100,
					Price = 0,
					Item = "Large DrPiper",
				},
			},
		},
		["Large Bloxy Cola"] = {
			Lvl = 6,
			Chance = 75,
			Price = 5.32,
			Amount = NumberRange.new(1,1),
			Ingredients = {
				{
					Lvl = 1,
					Chance = 100,
					Price = 0.,
					Item = "Large Bloxy Cola",
				},
			},
		},
		["Large Bug Rootbeer"] = {
			Lvl = 6,
			Chance = 75,
			Price = 5.32,
			Amount = NumberRange.new(1,1),
			Ingredients = {
				{
					Lvl = 1,
					Chance = 100,
					Price = 0,
					Item = "Large Bug Rootbeer",
				},
			},
		},
		["Nothing"] = {
			Chance = 10,
		},
	},
	["Dessert"] = {
		["Vanilla Ice Cream"] = {
			Lvl = 26,
			Chance = 75,
			Price = 9.32,
			Amount = NumberRange.new(1,1),
			Ingredients = {
				{
					Lvl = 1,
					Chance = 100,
					Price = 0.35,
					Item = "Vanilla Ice Cream",
				},
			},
		},
		["Strawberry Ice Cream"] = {
			Lvl = 26,
			Chance = 75,
			Price = 9.32,
			Amount = NumberRange.new(1,1),
			Ingredients = {
				{
					Lvl = 1,
					Chance = 100,
					Price = 0.35,
					Item = "Strawberry Ice Cream",
				},
			},
		},
		["Chocolate Ice Cream"] = {
			Lvl = 26,
			Chance = 75,
			Price = 9.32,
			Amount = NumberRange.new(1,1),
			Ingredients = {
				{
					Lvl = 1,
					Chance = 100,
					Price = 0.35,
					Item = "Chocolate Ice Cream",
				},
			},
		},
		["Nothing"] = {
			Chance = 10,
		},
	},
}