--!strict

return {
	["Grill"] = {
		Keypoints = {
			{ Duration = 20 },
			{ Duration = 20 },
			{ Duration = 0 },
		},
	},
	["Fryer"] = {
		Keypoints = {
			{ Duration = 25 },
			{ Duration = 0 },
		},
	},
	["DrinkDispenser"] = {
		Keypoints = {
			{ Duration = 0 },
			{ Duration = 10 },
			{ Duration = 0 },
		},
	},
	["IceCreamMaker"] = {
		Keypoints = {
			{ Duration = 0 },
			{ Duration = 8 },
			{ Duration = 0 },
		},
	},
	["Milkshake"] = {
		Keypoints = {
			{ Duration = 0 },
			{ Duration = 12 },
			{ Duration = 0 },
		},
	},
}
